<?php
// custom field help
add_action('add_meta_boxes', 'con_add_custom_box');

function con_add_custom_box() {
	//add to pages
	add_meta_box( 'con_custom_fields', __( 'Continuum Custom Field Guide - Pages', 'continuum' ), 'con_custom_fields_page', 'page', 'normal', 'core' );
	//add to regular posts
	add_meta_box( 'con_custom_fields', __( 'Continuum Custom Field Guide - Posts', 'continuum' ), 'con_custom_fields_post', 'post', 'normal', 'core' );
	//add to custom post types
	add_meta_box( 'con_custom_fields', __( 'Continuum Custom Field Guide - Reviews', 'continuum' ), 'con_custom_fields_review', 'con_movie_reviews', 'normal', 'core' );
	add_meta_box( 'con_custom_fields', __( 'Continuum Custom Field Guide - Reviews', 'continuum' ), 'con_custom_fields_review', 'con_music_reviews', 'normal', 'core' );
	add_meta_box( 'con_custom_fields', __( 'Continuum Custom Field Guide - Reviews', 'continuum' ), 'con_custom_fields_review', 'con_game_reviews', 'normal', 'core' );
	add_meta_box( 'con_custom_fields', __( 'Continuum Custom Field Guide - Reviews', 'continuum' ), 'con_custom_fields_review', 'con_book_reviews', 'normal', 'core' );
	add_meta_box( 'con_custom_fields', __( 'Continuum Custom Field Guide - Reviews', 'continuum' ), 'con_custom_fields_review', 'con_product_reviews', 'normal', 'core' );
}
function con_custom_fields_page() {
	echo '<style type="text/css">';
	echo '.ccfg th {background:#666;color:#FFF;padding:10px 10px;text-align:left;font-size:1.1em;}';
	echo '.ccfg td {padding:6px 10px;vertical-align:top;}';
	echo '.ccfg tr.alt td {background:#EEE;}';
	echo '.ccfg td.name {font-weight:bold; width:200px;}';
	echo '.ccfg td.values {width:200px;}';
	echo '.ccfg td.notes {font-size:.9em;color:#666;}';
	echo '</style>';
	echo '<p>'.__( 'This is a list of all possible custom field values that you can add to an individual page to overwrite the main settings on the Continuum Theme Options page.', 'continuum' ).'</p>';
	echo '<table class="ccfg" cellpadding="0" cellspacing="0">';
	echo '<tr><th>'.__( 'Name', 'continuum' ).'</th><th>'.__( 'Possible Values', 'continuum' ).'</th><th>'.__( 'Notes', 'continuum' ).'</th></tr>';
	echo '<tr><td class="name">Show Breaking Panel</td>';
	echo '<td class="values">true, false</td>';
	echo '<td class="notes">'.__( 'the slider above the header', 'continuum' ).'</td></tr>';
	echo '<tr class="alt"><td class="name">Featured Image Size</td>';
	echo '<td class="values">small, medium, full, none</td>';
	echo '<td class="notes"></td></tr>';
	echo '<tr><td class="name">Show Sharebox</td>';
	echo '<td class="values">true, false</td>';
	echo '<td class="notes">'.__( 'the panel below the featured image', 'continuum' ).'</td></tr>';
	echo '<tr class="alt"><td class="name">Show Feed</td>';
	echo '<td class="values">true, false</td>';
	echo '<td class="notes">'.__( 'the latest posts panel below the page content', 'continuum' ).'</td></tr>';
	echo '<tr><td class="name">Show Latest Panel</td>';
	echo '<td class="values">true, false</td>';
	echo '<td class="notes">'.__( 'the category-based latest posts panel above the footer', 'continuum' ).'</td></tr>';
	echo '<tr class="alt"><td class="name">Spotlight Layout</td>';
	echo '<td class="values">A, B, C</td>';
	echo '<td class="notes">'.__( 'only applies to pages with the Home Layout template', 'continuum' ).'</td></tr>';
	echo '<tr><td class="name">Spotlight Widgets</td>';
	echo '<td class="values">true, false</td>';
	echo '<td class="notes">'.__( 'the widget panel to the right of the slider which displays recent reactions by default (only applies to pages with the Home Layout template)', 'continuum' ).'</td></tr>';
	echo '<tr class="alt"><td class="name">Feed Layout</td>';
	echo '<td class="values">A, B, C, D</td>';
	echo '<td class="notes">'.__( 'the layout of the feed (only applies to pages with the Home Layout template that are not the front page)', 'continuum' ).'</td></tr>';
	echo '<tr><td class="name">Feed Header</td>';
	echo '<td class="values">[text]</td>';
	echo '<td class="notes">'.__( 'header text to use for the feed (only applies to pages with the Home Layout template that are not the front page)', 'continuum' ).'</td></tr>';
	echo '<tr class="alt"><td class="name">Feed Posts Per Page</td>';
	echo '<td class="values">1 - &infin;</td>';
	echo '<td class="notes">'.__( 'number of posts to display on each feed page - feeds are paginated (only applies to pages with the Home Layout template that are not the front page)', 'continuum' ).'</td></tr>';
	echo '<tr><td class="name">Feed Number Of Ads</td>';
	echo '<td class="values">1 - 10</td>';
	echo '<td class="notes">'.__( 'number of total ads to display in the feed (only applies to pages with the Home Layout template that are not the front page)', 'continuum' ).'</td></tr>';
	echo '<tr class="alt"><td class="name">Feed Ad Increment</td>';
	echo '<td class="values">2 - &infin;</td>';
	echo '<td class="notes">'.__( 'ads appear every nth post, where "n" is the increment (only applies to pages with the Home Layout template that are not the front page)', 'continuum' ).'</td></tr>';
	echo '<tr><td class="name">Feed Offset</td>';
	echo '<td class="values">0 - &infin;</td>';
	echo '<td class="notes">'.__( 'number of posts to display before the first ad (only applies to pages with the Home Layout template that are not the front page)', 'continuum' ).'</td></tr>';
	echo '<tr class="alt"><td class="name">Feed Layout D Header</td>';
	echo '<td> class="values"[text]</td>';
	echo '<td class="notes">'.__( 'if using layout D, specify header text (only applies to pages with the Home Layout template that are not the front page)', 'continuum' ).'</td></tr>';
	echo '<tr><td class="name">Latest Panel Position</td>';
	echo '<td class="values">above, below</td>';
	echo '<td class="notes">'.__( 'display the latest panel above or below the feed (only applies to pages with the Home Layout template)', 'continuum' ).'</td></tr>';
	echo '<tr class="alt"><td class="name">Show Ad In Header</td>';
	echo '<td class="values">true, false</td>';
	echo '<td class="notes"></td></tr>';
	echo '<tr><td class="name">Show Ad Below Post</td>';
	echo '<td class="values">true, false</td>';
	echo '<td class="notes"></td></tr>';
	echo '<tr class="alt"><td class="name">Show Ad Below Feed</td>';
	echo '<td class="values">true, false</td>';
	echo '<td class="notes"></td></tr>';
	echo '</table>';
}
function con_custom_fields_post() {
	echo '<style type="text/css">';
	echo '.ccfg th {background:#666;color:#FFF;padding:10px 10px;text-align:left;font-size:1.1em;}';
	echo '.ccfg td {padding:6px 10px;vertical-align:top;}';
	echo '.ccfg tr.alt td {background:#EEE;}';
	echo '.ccfg td.name {font-weight:bold; width:200px;}';
	echo '.ccfg td.values {width:200px;}';
	echo '.ccfg td.notes {font-size:.9em;color:#666;}';
	echo '</style>';
	echo '<p>'.__( 'This is a list of all possible custom field values that you can add to an individual post to overwrite the main settings on the Continuum Theme Options page.', 'continuum' ).'</p>';
	echo '<table class="ccfg" cellpadding="0" cellspacing="0">';
	echo '<tr><th>'.__( 'Name', 'continuum' ).'</th><th>'.__( 'Possible Values', 'continuum' ).'</th><th>'.__( 'Notes', 'continuum' ).'</th></tr>';
	echo '<tr><td class="name">Show Breaking Panel</td>';
	echo '<td class="values">true, false</td>';
	echo '<td class="notes">'.__( 'the slider above the header', 'continuum' ).'</td></tr>';
	echo '<tr class="alt"><td class="name">Featured Image Size</td>';
	echo '<td class="values">small, medium, full, none</td>';
	echo '<td class="notes"></td></tr>';
	echo '<tr><td class="name">Show Infobox</td>';
	echo '<td class="values">true, false</td>';
	echo '<td class="notes">'.__( 'the panel below the post title with the author info &amp; tags', 'continuum' ).'</td></tr>';
	echo '<tr class="alt"><td class="name">Show Sharebox</td>';
	echo '<td class="values">true, false</td>';
	echo '<td class="notes">'.__( 'the panel below the featured image', 'continuum' ).'</td></tr>';
	echo '<tr><td class="name">Show Authorbox</td>';
	echo '<td class="values">true, false</td>';
	echo '<td class="notes">'.__( 'the panel below the post content with the author bio', 'continuum' ).'</td></tr>';
	echo '<tr class="alt"><td class="name">Show Feed</td>';
	echo '<td class="values">true, false</td>';
	echo '<td class="notes">'.__( 'the latest posts panel below the page content', 'continuum' ).'</td></tr>';
	echo '<tr><td class="name">Show Latest Panel</td>';
	echo '<td class="values">true, false</td>';
	echo '<td class="notes">'.__( 'the category-based latest posts panel above the footer', 'continuum' ).'</td></tr>';
	echo '<tr class="alt"><td class="name">Feed Header</td>';
	echo '<td class="values">[text]</td>';
	echo '<td class="notes">'.__( 'header text to use for the feed', 'continuum' ).'</td></tr>';
	echo '<tr><td class="name">Feed Posts Per Page</td>';
	echo '<td class="values">1 - &infin;</td>';
	echo '<td class="notes">'.__( 'number of posts to display on each feed page - feeds are paginated', 'continuum' ).'</td></tr>';
	echo '<tr class="alt"><td class="name">Feed Number Of Ads</td>';
	echo '<td class="values">1 - 10</td>';
	echo '<td class="notes">'.__( 'number of total ads to display in the feed', 'continuum' ).'</td></tr>';
	echo '<tr><td class="name">Feed Ad Increment</td>';
	echo '<td class="values">2 - &infin;</td>';
	echo '<td class="notes">'.__( 'ads appear every nth post, where "n" is the increment', 'continuum' ).'</td></tr>';
	echo '<tr class="alt"><td class="name">Feed Offset</td>';
	echo '<td class="values">0 - &infin;</td>';
	echo '<td class="notes">'.__( 'number of posts to display before the first ad', 'continuum' ).'</td></tr>';
	echo '<tr><td class="name">Show Ad In Header</td>';
	echo '<td class="values">true, false</td>';
	echo '<td class="notes"></td></tr>';
	echo '<tr class="alt"><td class="name">Show Ad Below Post</td>';
	echo '<td class="values">true, false</td>';
	echo '<td class="notes"></td></tr>';
	echo '<tr><td class="name">Show Ad Below Feed</td>';
	echo '<td class="values">true, false</td>';
	echo '<td class="notes"></td></tr>';
	echo '</table>';
}
function con_custom_fields_review() {
	echo '<style type="text/css">';
	echo '.ccfg th {background:#666;color:#FFF;padding:10px 10px;text-align:left;font-size:1.1em;}';
	echo '.ccfg td {padding:6px 10px;vertical-align:top;}';
	echo '.ccfg tr.alt td {background:#EEE;}';
	echo '.ccfg td.name {font-weight:bold; width:200px;}';
	echo '.ccfg td.values {width:200px;}';
	echo '.ccfg td.notes {font-size:.9em;color:#666;}';
	echo '</style>';
	echo '<p>'.__( 'This is a list of all possible custom field values that you can add to an individual review to overwrite the main settings on the Continuum Theme Options page.', 'continuum' ).'</p>';
	echo '<table class="ccfg" cellpadding="0" cellspacing="0">';
	echo '<tr><th>'.__( 'Name', 'continuum' ).'</th><th>'.__( 'Possible Values', 'continuum' ).'</th><th>'.__( 'Notes', 'continuum' ).'</th></tr>';
	echo '<tr><td class="name">Show Breaking Panel</td>';
	echo '<td class="values">true, false</td>';
	echo '<td class="notes">'.__( 'the slider above the header', 'continuum' ).'</td></tr>';
	echo '<tr class="alt"><td class="name">Show Sharebox</td>';
	echo '<td class="values">true, false</td>';
	echo '<td class="notes">'.__( 'the panel below the featured image', 'continuum' ).'</td></tr>';
	echo '<tr><td class="name">Show Authorbox</td>';
	echo '<td class="values">true, false</td>';
	echo '<td class="notes">'.__( 'the panel below the post content with the author bio', 'continuum' ).'</td></tr>';
	echo '<tr class="alt"><td class="name">Award</td>';
	echo '<td class="values">[text]</td>';
	echo '<td class="notes">'.__( 'displays an award badge in the header of a review and displays the text entered as the award name', 'continuum' ).'</td></tr>';
	echo '<tr><td class="name">Positives</td>';
	echo '<td class="values">[text]</td>';
	echo '<td class="notes">'.__( 'short summary of the positives of this review', 'continuum' ).'</td></tr>';
	echo '<tr class="alt"><td class="name">Negatives</td>';
	echo '<td class="values">[text]</td>';
	echo '<td class="notes">'.__( 'short summary of the negatives of this review', 'continuum' ).'</td></tr>';
	echo '<tr><td class="name">Rating</td>';
	echo '<td class="values">0, 0.5, 1, 1.5, 2, 2.5, 3, 3.5, 4, 4.5, 5 stars (or hearts)</td>';
	echo '<td class="notes">'.__( 'the rating for this review out of 5 - <b>add "hearts" after the number to display hearts instead of stars for the rating</b> (e.g. "3.5 hearts" instead of "3.5 stars") you can also just use a number for stars (i.e. "3.5" will display stars)', 'continuum' ).'</td></tr>';
	echo '<tr class="alt"><td class="name">Show Feed</td>';
	echo '<td class="values">true, false</td>';
	echo '<td class="notes">'.__( 'the latest posts panel below the page content', 'continuum' ).'</td></tr>';
	echo '<tr><td class="name">Show Latest Panel</td>';
	echo '<td class="values">true, false</td>';
	echo '<td class="notes">'.__( 'the category-based latest posts panel above the footer', 'continuum' ).'</td></tr>';
	echo '<tr class="alt"><td class="name">Feed Header</td>';
	echo '<td class="values">[text]</td>';
	echo '<td class="notes">'.__( 'header text to use for the feed', 'continuum' ).'</td></tr>';
	echo '<tr><td class="name">Feed Posts Per Page</td>';
	echo '<td class="values">1 - &infin;</td>';
	echo '<td class="notes">'.__( 'number of posts to display on each feed page - feeds are paginated', 'continuum' ).'</td></tr>';
	echo '<tr class="alt"><td class="name">Feed Number Of Ads</td>';
	echo '<td class="values">1 - 10</td>';
	echo '<td class="notes">'.__( 'number of total ads to display in the feed', 'continuum' ).'</td></tr>';
	echo '<tr><td class="name">Feed Ad Increment</td>';
	echo '<td class="values">2 - &infin;</td>';
	echo '<td class="notes">'.__( 'ads appear every nth post, where "n" is the increment', 'continuum' ).'</td></tr>';
	echo '<tr class="alt"><td class="name">Feed Offset</td>';
	echo '<td class="values">0 - &infin;</td>';
	echo '<td class="notes">'.__( 'number of posts to display before the first ad', 'continuum' ).'</td></tr>';
	echo '<tr><td class="name">Show Ad In Header</td>';
	echo '<td class="values">true, false</td>';
	echo '<td class="notes"></td></tr>';
	echo '<tr class="alt"><td class="name">Show Ad Below Post</td>';
	echo '<td class="values">true, false</td>';
	echo '<td class="notes"></td></tr>';
	echo '<tr><td class="name">Show Ad Below Feed</td>';
	echo '<td class="values">true, false</td>';
	echo '<td class="notes"></td></tr>';
	echo '</table>';
}
?>